### PR TITLE
add jest framework to backend, wait to be improved

### PR DESCRIPTION
**Pull request by ly3ly**

### CODE REVIEW

**Review by ahhuh-ly — COMMENTED** [review]
Changes approved.

**Review by lajiaopingzi — APPROVED** [review]
agree

**Comment by AnnieKJR** [comment]
Approve. The addition of Jest is a significant improvement, and it is crucial to consider the extent of test coverage.

**Review by AnnieKJR — APPROVED** [review]
Inorder to ensure consistency across the project and assist new contributors in understanding how to write effective tests, you could consider incorporate clear documentation and guidelines for writing tests using Jest if possible. :)

**Review by JasmineLSQ — APPROVED** [review]

**Pull request merged**
